<a href="https://colab.research.google.com/github/Huxaifax/TensorFlow-/blob/main/pytorch_basics_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
t1 = torch.tensor(4.)
t1

tensor(4.)

In [3]:
t1.dtype

torch.float32

In [5]:
t2 = torch.tensor([1.,2,3,4])
t2

tensor([1., 2., 3., 4.])

In [6]:
t3 = torch.tensor([[5,6],[2,7],[9,10]])
t3

tensor([[ 5,  6],
        [ 2,  7],
        [ 9, 10]])

In [7]:
t4 = torch.tensor([
                   [[11,12,13],
                    [13,14,11]],
                    [[15,16,17],
                    [17,18,19]]
])
t4

tensor([[[11, 12, 13],
         [13, 14, 11]],

        [[15, 16, 17],
         [17, 18, 19]]])

In [8]:
t1.shape

torch.Size([])

In [9]:
t2.shape

torch.Size([4])

In [10]:
t3.shape

torch.Size([3, 2])

In [11]:
t4.shape

torch.Size([2, 2, 3])

**Tensors and gradients**

In [12]:
x = torch.tensor(3.0)
w = torch.tensor(4.0 , requires_grad=True)
b = torch.tensor(5.0 , requires_grad=True)

In [13]:
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

In [14]:
y.backward()

the derviavte of y wrt the input tensors are stored in .grad property of the respective tensor.

In [15]:
print('dy/dx:',x.grad)
print('dy/dw:',w.grad)
print('dy/db:',b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


**Interoperability with Numpy**

In [16]:
import numpy as np

x = np.array([[1,2],[3,4.0]])
x

array([[1., 2.],
       [3., 4.]])

In [18]:
y = torch.from_numpy(x)
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [19]:
x.dtype, y.dtype

(dtype('float64'), torch.float64)

In [21]:
z = y.numpy()
z

array([[1., 2.],
       [3., 4.]])