<a href="https://colab.research.google.com/github/Huxaifax/TensorFlow-/blob/main/pytorch_linear_reg.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import torch

In [3]:
inputs = np.array([[73,67,43],
                   [91,88,64],
                   [87,134,58],
                   [102,43,37],
                   [69,96,70]], dtype='float32')

In [4]:
targets = np.array([[56,70],
                   [81,101],
                   [119,133],
                   [22,37],
                   [103,119]], dtype='float32')

In [5]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [6]:
w = torch.randn(2,3, requires_grad=True)
b = torch.randn(2, requires_grad=True)
print(w)
print(b)

tensor([[-0.9603,  0.3863,  0.3112],
        [-0.2970, -0.5172,  1.2561]], requires_grad=True)
tensor([-0.3038,  1.5871], requires_grad=True)


In [16]:
def model(x):
  return x @ w.t() + b

In [17]:
preds = model(inputs)
print(preds)

tensor([[-31.1462,  -0.7352],
        [-33.7849,   9.4353],
        [-14.0430, -20.7046],
        [-70.1337,  -4.4721],
        [ -7.7000,  19.3684]], grad_fn=<AddBackward0>)


In [20]:
diff = preds - targets
diff_sqr = diff * diff
torch.sum(diff_sqr) / diff.numel()

tensor(10787.2656, grad_fn=<DivBackward0>)

In [21]:
def mse(t1, t2):
  diff = t1 - t2
  return torch.sum(diff * diff) / diff.numel()

In [22]:
loss = mse(preds, targets)
print(loss)

tensor(10787.2656, grad_fn=<DivBackward0>)


In [23]:
loss.backward()

In [25]:
print(w)
print(w.grad)

tensor([[-0.9603,  0.3863,  0.3112],
        [-0.2970, -0.5172,  1.2561]], requires_grad=True)
tensor([[-9083.5557, -9671.3154, -5993.5923],
        [-7594.6196, -8948.2627, -5265.0615]])


In [26]:
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


In [27]:
preds = model(inputs)
print(preds)

tensor([[-31.1462,  -0.7352],
        [-33.7849,   9.4353],
        [-14.0430, -20.7046],
        [-70.1337,  -4.4721],
        [ -7.7000,  19.3684]], grad_fn=<AddBackward0>)


In [28]:
loss = mse(preds, targets)
print(loss)

tensor(10787.2656, grad_fn=<DivBackward0>)


In [29]:
loss.backward()
print(w.grad)
print(b.grad)

tensor([[-9083.5557, -9671.3154, -5993.5923],
        [-7594.6196, -8948.2627, -5265.0615]])
tensor([-107.5616,  -91.4217])


In [31]:
with torch.no_grad():
  w-=w.grad * 1e-5
  b -=b.grad *1e-5
  w.grad.zero_()
  b.grad.zero_()

In [32]:
print(w)
print(b)

tensor([[-0.7787,  0.5797,  0.4311],
        [-0.1451, -0.3382,  1.3614]], requires_grad=True)
tensor([-0.3017,  1.5889], requires_grad=True)


In [33]:
preds = model(inputs)
loss = mse(preds, targets)
loss

tensor(4589.0879, grad_fn=<DivBackward0>)

In [37]:
for i in range(1000):
  preds = model(inputs)
  loss = mse(preds, targets)
  loss.backward()
  with torch.no_grad():
    w-=w.grad * 1e-5
    b -=b.grad *1e-5
    w.grad.zero_()
    b.grad.zero_()

In [38]:
preds = model(inputs)
loss = mse(preds, targets)
loss

tensor(3.6418, grad_fn=<DivBackward0>)