<a href="https://colab.research.google.com/github/Huxaifax/TensorFlow-/blob/main/pytorch_linear_reg_build_ins.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [39]:
import torch.nn as nn

In [41]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70], 
                   [74, 66, 43], 
                   [91, 87, 65], 
                   [88, 134, 59], 
                   [101, 44, 37], 
                   [68, 96, 71], 
                   [73, 66, 44], 
                   [92, 87, 64], 
                   [87, 135, 57], 
                   [103, 43, 36], 
                   [68, 97, 70]], 
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119],
                    [57, 69], 
                    [80, 102], 
                    [118, 132], 
                    [21, 38], 
                    [104, 118], 
                    [57, 69], 
                    [82, 100], 
                    [118, 134], 
                    [20, 38], 
                    [102, 120]], 
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [42]:
from torch.utils.data import TensorDataset 

In [47]:
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]), tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [48]:
from torch.utils.data import DataLoader

In [49]:
batch_size = 5
train_dl = DataLoader(train_ds,batch_size, shuffle = True)

In [50]:
for xb, yb in train_dl:
  print(xb)
  print(yb)
  break

tensor([[ 87., 134.,  58.],
        [101.,  44.,  37.],
        [ 73.,  66.,  44.],
        [ 68.,  97.,  70.],
        [ 69.,  96.,  70.]])
tensor([[119., 133.],
        [ 21.,  38.],
        [ 57.,  69.],
        [102., 120.],
        [103., 119.]])


In [53]:
model = nn.Linear(3,2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[-0.0859,  0.5380, -0.4807],
        [ 0.2650,  0.2243,  0.1064]], requires_grad=True)
Parameter containing:
tensor([-0.3448, -0.1101], requires_grad=True)


In [54]:
list(model.parameters())

[Parameter containing:
 tensor([[-0.0859,  0.5380, -0.4807],
         [ 0.2650,  0.2243,  0.1064]], requires_grad=True),
 Parameter containing:
 tensor([-0.3448, -0.1101], requires_grad=True)]

In [55]:
preds = model(inputs)
preds

tensor([[ 8.7629, 38.8406],
        [ 8.4210, 50.5554],
        [36.3968, 59.1756],
        [-3.7563, 40.5053],
        [11.7307, 47.1570],
        [ 8.1390, 38.8813],
        [ 7.4023, 50.4375],
        [35.8303, 59.5470],
        [-3.1324, 40.4646],
        [11.3360, 46.9983],
        [ 7.7442, 38.7226],
        [ 7.7971, 50.5962],
        [37.4155, 59.2936],
        [-3.3615, 40.6640],
        [12.3546, 47.1163]], grad_fn=<AddmmBackward0>)

In [57]:
import torch.nn.functional as F

In [58]:
loss_fn = F.mse_loss

In [59]:
loss = loss_fn(model(inputs), targets)
print(loss)

tensor(3738.7390, grad_fn=<MseLossBackward0>)


In [61]:
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

In [64]:
def fit(num_epochs, model, loss_fn, opt):
  for epoch in range(num_epochs):

    pred = model(xb)

    loss = loss_fn(pred, yb)

    loss.backward()

    opt.step()

    opt.zero_grad()
  
    if(epoch+1)% 10 ==0:
      print("Epoch [{}/{}], Loss:{:.4f}".format(epoch+1,num_epochs,loss.item()))

In [65]:
fit(100, model, loss_fn, opt)

Epoch [10/100], Loss:150.7932
Epoch [20/100], Loss:138.0272
Epoch [30/100], Loss:126.6796
Epoch [40/100], Loss:116.5818
Epoch [50/100], Loss:107.5855
Epoch [60/100], Loss:99.5604
Epoch [70/100], Loss:92.3915
Epoch [80/100], Loss:85.9783
Epoch [90/100], Loss:80.2318
Epoch [100/100], Loss:75.0738


In [67]:
preds = model(inputs)
preds

tensor([[ 59.6064,  73.4919],
        [ 79.0762, 100.3174],
        [129.5453, 136.1940],
        [ 29.0432,  49.3766],
        [ 91.2059, 110.7419],
        [ 58.3630,  72.6138],
        [ 77.9803,  99.9526],
        [129.3682, 136.6275],
        [ 30.2866,  50.2547],
        [ 91.3533, 111.2553],
        [ 58.5104,  73.1272],
        [ 77.8329,  99.4392],
        [130.6413, 136.5588],
        [ 28.8958,  48.8632],
        [ 92.4492, 111.6201]], grad_fn=<AddmmBackward0>)

In [68]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])